"""Generate honest public examples from original synthetic images and frozen models."""

import json
from datetime import datetime, timezone
from pathlib import Path
from uuid import NAMESPACE_URL, uuid5

from PIL import Image

from receiptlab.assisted import assisted_extract
from receiptlab.ml import get_predictor
from receiptlab.ocr import run_ocr
from receiptlab.worker import normalize_extraction

ROOT = Path(__file__).resolve().parents[1]


def main():
    predictor = get_predictor(ROOT / "models")
    documents, audit = [], {}
    for name in ("sample-a", "sample-b", "sample-c"):
        source = ROOT / "frontend" / "public" / "samples" / f"{name}.png"
        with Image.open(source) as image:
            width, height = image.size
            extraction = normalize_extraction(assisted_extract(run_ocr(image), predictor))
        identifier = str(uuid5(NAMESPACE_URL, "receiptlab/synthetic/" + name))
        document = {
            "id": identifier,
            "filename": name + ".png",
            "source": "synthetic portfolio sample",
            "width": width,
            "height": height,
            "page_count": 1,
            "revision": 2,
            "status": "needs_review",
            "created_at": "2026-10-01T12:00:00+00:00",
            "image_url": "samples/" + name + ".png",
            "extraction": extraction,
        }
        documents.append(document)
        audit[identifier] = [
            {
                "event": "synthetic_sample_created",
                "revision": 1,
                "created_at": document["created_at"],
                "after": {"source": "Original image generated by scripts/make_samples.py"},
            },
            {
                "event": "extracted",
                "revision": 2,
                "created_at": datetime.now(timezone.utc).isoformat(),
                "after": extraction,
            },
        ]
        print(
            name,
            {key: field["value"] for key, field in extraction["fields"].items()},
            len(extraction["items"]),
            flush=True,
        )
    metrics = json.loads((ROOT / "reports" / "evaluation.json").read_text(encoding="utf-8"))
    for key, filename in [
        ("transformer", "transformer-evaluation.json"),
        ("assisted", "test-assisted-evaluation.json"),
    ]:
        report = ROOT / "reports" / filename
        if report.is_file():
            metrics[key] = json.loads(report.read_text(encoding="utf-8"))
    output = ROOT / "frontend" / "public" / "demo-data.json"
    output.write_text(
        json.dumps({"documents": documents, "audit": audit, "metrics": metrics}, indent=2),
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
